bot:
  token: "eyrtjyhfh5436rutyhfgw45r6utyfg"
  send_chat_id: "-123123123123"

scanner:
  maximum_scanning_blocks: 500
  confirmation_blocks: 10
  speedy_polling_interval: 5
  polling_interval: 30

web3:
  provider_url: https://rpc.flashbots.net

contracts:
  aix_treasury: "0xaBE235136562a5C2B02557E1CaE7E8c85F2a5da0"
